Features/token ablations
curt-tigges/exploring-summarization pull request #1
Opened 2023-10-27 06:48 UTC by curt-tigges

Added a variety of utils and experiment functions for tokenwise experiments. These are designed to be used with a HuggingFace Dataset that contains tokens, masks, and 1/0 position vectors that demarcate where instances of a given token are present.

Also includes functions for creating layerwise mean residual stream vectors for the given token.

2023-10-27 20:07 UTC, ojh31 requested changes
Great work on this! Key issues for me:

- You make assumptions about the content of the dataloader objects which are a bit opaque. It would be great if you could use some OOP tricks to make this really clear, i.e. create subclasses of DataLoader with methods for converting between formats and detailed docstrings
- There are a few very similar methods along the lines of perform some tokenwise ablations and compute a metric. To reduce the pain of maintenance, I think it would be good to combine these where possible and use kwargs to differentiate the different use cases.

2023-10-27 20:07 UTC, ojh31 commented on utils/tokenwise_ablation.py
> +def compute_zeroed_attn_modified_loss(model: HookedTransformer, data_loader: DataLoader, heads_to_ablate) -> float:
split up line, type hint `heads_to_ablate`

2023-10-27 20:07 UTC, ojh31 commented on utils/tokenwise_ablation.py
> +        loss_diff[shifted_punct_pos == 1] = 0
Need to discuss this in docstring

2023-10-27 21:22 UTC, curt-tigges commented on utils/experiments.py
Yep, deleted now

2023-10-27 21:22 UTC, curt-tigges commented on Dockerfile.backup
Removed this

2023-11-03 11:00 UTC, ojh31 approved these changes

2023-11-03 11:11 UTC, merged