Features/token ablations
curt-tigges/exploring-summarization pull request #9
Opened 2023-11-09 21:58 UTC by curt-tigges

# Description

I've added separate functions for getting loss and logit diff. Can ignore the notebook changes (just some random tests) and the period ablation stuff (which is in progress).

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
- [ ] I have followed the style guide below

# Style guide
- My code follows the [Black](https://pypi.org/project/black/) format
- I have minimised type warnings from [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)
- Cull any redundant and unused code
- Cache results of slow operations in as flexible of a format as possible, in a flat structure inside results/cache and the file name contains all necessary identifying information (such as model name and dataset used) to avoid accidental overwriting.
- Use intuitive abstractions, making clear the public entrypoints to a given class
- Function and variable names should be long enough to be descriptive

2023-11-09 22:22 UTC, curt-tigges commented
@ojh31 I noticed that somewhere in the process of rebasing, the function mask_loss_at_next_positions disappeared. What was the intended replacement for this?

2023-11-10 17:20 UTC, ojh31 commented
> @ojh31 I noticed that somewhere in the process of rebasing, the function mask_loss_at_next_positions disappeared. What was the intended replacement for this?

It was replaced by [this](https://github.com/curt-tigges/exploring-summarization/blob/8d397f9f89a188fdee7e89d15dd99cfbdb12dac3/utils/datasets.py#L144). The idea is we should really just cache all of the losses and then after loading the cache you can mask however you like. I tried to unite the different cases we want to mask into one function.

2023-11-10 17:30 UTC, ojh31 requested changes
Just need to remove the reference to `mask_loss_at_next_positions` and then this is good to merge

2023-11-10 17:30 UTC, ojh31 commented on utils/tokenwise_ablation.py
> +    cached: bool = True,
Should we not remove this function now?

2023-11-10 17:30 UTC, ojh31 commented on utils/tokenwise_ablation.py
> +    item_len = len(data_loader.dataset[0]["tokens"])
Good catch, this is safer than using `n_ctx`

2023-11-10 17:30 UTC, ojh31 commented on utils/tokenwise_ablation.py
> +        ablated_metric = mask_loss_at_next_positions(
Should remove this reference to the old masking function and cache all of the loss diffs here

2023-11-10 17:30 UTC, ojh31 commented on utils/tokenwise_ablation.py
> +def compute_ablation_modified_logit_diff(
Ideally it would be nice to have some sort of documentation where we compare and contrast the similarly named functions in this file

2023-11-11 12:33 UTC, merged